version: "3"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
    depends_on:
      - cadvisor

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "4000:4000"
    volumes:
      - .:/app  # Mapeando o diretório local para o diretório do aplicativo dentro do contêiner
    networks:
      - monitoring
    command: ["npm", "run", "dev"]  # Inicie o servidor com nodemon

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/kmsg:/dev/kmsg
    privileged: true
    depends_on:
      - redis
    networks:
      - monitoring

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6380:6380
    networks:
      - monitoring

volumes:
  grafana_data:

networks:
  monitoring:
